### PR TITLE
Add auto-translate subtitles

### PR DESCRIPTION
**Pull request by PeterNjeim**
Based on yt-dlp's implementation ([yt_dlp/extractor/youtube.py#L3637-L3699](https://github.com/yt-dlp/yt-dlp/blob/96623ab5c6cea59c22395a47f00a13d334de6106/yt_dlp/extractor/youtube.py#L3637-L3699))

- [x] Download automatically-translated subtitles
- [ ]  Create UI button in subtitle menu to select automatically translated subtitles
- [ ] Separate automatically-translated subtitle tracks from human-generated and auto-generated subtitle tracks
- [x] Support restricted videos (workaround: https://github.com/yt-dlp/yt-dlp/pull/3233) (another workaround is to simply append the `tlang` URL parameter at the end of the baseURL's for the subtitles that already exist (since for those ones you already bypassed the age-restriction). However, you would need to keep up with YouTube whenever they change what auto-translated languages are available, and also provide the language names yourself)
- [ ] Clean code (remove uneeded code)
- [ ] Localize to other languages
- [ ] Make system to choose which subtitle to translate from by default (probably the best way is to choose the human-generated translation of the language of the video (which will also have an auto-generated version), and if that doesn't exist, choose the most popular language from the human-generated subtitles (by population), and if there aren't any human-generated subtitles, choose the auto-generated one. This feature would be to have subtitles in the user's chosen language without needing their input. So if they chose Spanish, even if a video didn't have Spanish subtitles, it would show the auto-translated Spanish subtitles by choosing the best non-translated subtitle, and of course showing the human-translated Spanish subtitles if it exists)

Resolves https://github.com/yuliskov/SmartTubeNext/issues/244
Resolves https://github.com/yuliskov/SmartTubeNext/issues/1407
Resolves https://github.com/yuliskov/SmartTubeNext/issues/1741
Resolves https://github.com/yuliskov/SmartTubeNext/issues/1745

### CODE REVIEW

**Comment by PeterNjeim** [comment]
Currently the subtitles "overlap" and so it doesn't show all the possibilites, this is on purpose since I plan on making a separate menu just like the desktop YouTube version

**Comment by PeterNjeim** [comment]
Basically, what I did was make something called PageInfo, which is similar to VideoInfo, and I also made something called RegExpAndJsonPath, which is similar to both RegExp and JsonPath. Then I added the boilerplate in the service folder and that's pretty much it.

**Comment by yuliskov** [comment]
Thanks, friend. I'll check the pull request.

**Comment by PeterNjeim** [comment]
It's in draft mode right now, since I plan on fixing up the remaining tasks, so no need to review it currently unless you want to change the direction I'm going with it right now

**Comment by yuliskov** [comment]
@PeterNjeim agreed. The code should be checked first. Maybe I'll do the rest.

**Comment by PeterNjeim** [comment]
Not related to this PR but I do have quite a few other things I plan on working on for this project (just sharing it so you know what I'm up to and can have an opinion on it):

- [ ] Implement animation for auto-generated captions (since they scroll one line at a time, it's more legibile if it smoothly scrolls up line-by-line, just like on YouTube's website (maybe even word-by-word just like the website too, but that's probably too hard or unnecessary)
- [ ] Implement comments section (with liking, disliking, replying, read more, view channel, share link, copy text, clicking links in comments, viewing replies, sort by newest, top, or timed, basically everything)
- [ ] Implement Return YouTube Dislike extension (to show like and dislike counts, with ratio bar as well)
- [ ] Implement multiline scroll for title text (snake/Z scroll. Currently titles show 2 lines of text, but when they scroll it shows only one line, making a weird situation where you read what you already read. Instead of doing that, you can make it scroll like a Z shape, I'm sure you can visualize it)
- [ ] Fix RTL title scroll (currently RTL scripts like Arabic Hebrew scroll incorrectly for long titles, it's hard to explain but it seems to start and stop at the wrong position (this also applies to long channel names when they scroll too))
- [ ] Fix bi-directional channel names conflicting with view count (Arabic text in a channel name will have a weird effect with the view count (450K views). It gets jumbled and hard to read, proper bi-directional support would fix it)
- [ ] Implement auto-play delay (configurable in settings) (with thumbnail of next video, continue, and cancel buttons) when not in a playlist (especially with sponsorblock, too many times the next video will play when I didn't plan on watching it, and I have to remove it from my history, a delay just like the YouTube website would be nice (excluding playlists))
- [ ] Stop auto-play when viewing suggestions (just like the YouTube website, disable the auto-play feature when a button that is not part of the video player is in focus, or if you're in any menu) (and if the auto-play delay is enabled, make it restart the delay when you scroll back up, just like the YouTube website)
- [ ] Button to download video/audio (don't know if you desire this functionality in your app)

**Comment by PeterNjeim** [comment]
I'm having lots of trouble with this. As far as I can tell, in PlayerUIManager, I can't dynamically change the settingsPresenter after showDialog is called, meaning there's no way to make a category for auto-translated subtitles which dynamically updates its options to match the selected subtitle (if user selects Spanish subtitles, show subtitles translated from Spanish). If there are multiple human-translated languages, the number of auto-translated languages gets very large, on some popular videos it's over 1500, so showing all the subtitles is not an option. Is there any way you could make it so that there could be a dynamic radio category for the settingsPresenter? If not, as a workaround users would need to click back twice to go to the player UI, and then click on the subtitles button a second time to enable the auto-translate option.

**Comment by yuliskov** [comment]
Seems that I've found an easier way for this. Thanks for your efforts.

**Pull request closed without merging**
